// Generated by LiveScript 1.2.0
(function(){
  var myApp;
  myApp = angular.module('myApp', ['infinite-scroll']);
  myApp.controller('DemoController', function($scope){
    $scope.images = [1, 2, 3, 4, 5, 6, 7, 8];
    return $scope.loadMore = function(){
      var last, i$, i, results$ = [];
      last = $scope.images[$scope.images.length - 1];
      for (i$ = 0; i$ <= 7; ++i$) {
        i = i$;
        results$.push($scope.images.push(last + i));
      }
      return results$;
    };
  });
}).call(this);
