// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    debugging: false,
    hasDebug: function(){
      return this.debugging || constructor.debugAll;
    },
    debug: function(){
      var constr;
      if (this.hasDebug()) {
        constr = this.constructor.displayName || this.displayName;
        console.log(constr + ':');
        return console.log.apply(this, arguments);
      }
    },
    infoMsg: function(){
      if (this.debugging || constructor.debugAll) {
        return console.log.apply(this, arguments);
      }
    },
    debugAllOn: function(){
      return this.debugAll = true;
    },
    debugAllOff: function(){
      return this.debugAll = false;
    },
    debugOn: function(){
      return this.debugging = true;
    },
    debugOff: function(){
      return this.debugging = false;
    }
  };
}).call(this);
