// Generated by LiveScript 1.2.0
(function(){
  var ScrollConfig;
  ScrollConfig = (function(){
    ScrollConfig.displayName = 'ScrollConfig';
    var prototype = ScrollConfig.prototype, constructor = ScrollConfig;
    function ScrollConfig(){
      this.reset();
    }
    prototype.reset = function(){
      this.scrollDistance = null;
      this.scrollEnabled = null;
      this.checkWhenEnabled = null;
      this.container = null;
      return this.immediateCheck = true;
    };
    prototype.toggleEnabled = function(value){
      return this.config.scrollEnabled = !(value || this.config.scrollEnabled);
    };
    prototype.isScrollEnabled = function(){
      return this.scrollEnabled && this.checkWhenEnabled;
    };
    prototype.setScrollDistance = function(value){
      return this.scrollDistance = parseInt(value, 10) || 0;
    };
    prototype.disableScroll = function(){
      return this.checkWhenEnabled = false;
    };
    prototype.enableScroll = function(){
      var checkWhenEnabled;
      return checkWhenEnabled = true;
    };
    return ScrollConfig;
  }());
  module.exports = ScrollConfig;
}).call(this);
