// Generated by LiveScript 1.2.0
(function(){
  var ScrollHandler;
  require('./debugger');
  ScrollHandler = (function(){
    ScrollHandler.displayName = 'ScrollHandler';
    var prototype = ScrollHandler.prototype, constructor = ScrollHandler;
    importAll$(prototype, arguments[0]);
    function ScrollHandler(scope, config){
      this.scope = scope;
      this.config = config;
      this.container = this.config.container;
      this.elem = this.config.elem;
      this.scrollDistance = this.config.scrollDistance;
      this.scrollEnabled = this.config.scrollEnabled;
      this;
    }
    prototype.handleScroll = function(){
      if (this.shouldScroll()) {
        return this.scroll();
      }
    };
    prototype.isWindowContainer = function(){
      return this.container === $window;
    };
    prototype.scroll = function(){
      if (this.scrollEnabled) {
        return this.performScroll();
      } else {
        return this.enableScroll();
      }
    };
    prototype.performScroll = function(){
      this.configureScroll();
      return this.scope.infiniteScroll();
    };
    prototype.enableScroll = function(){
      return this.config.enableScroll();
    };
    prototype.configureScroll = function(){
      if (this.isWindowContainer()) {
        return this.configWindowScroll();
      } else {
        return this.configContainerScroll();
      }
    };
    prototype.shouldScroll = ScrollHandler.remaining() <= ScrollHandler.scrollBoundary();
    prototype.scrollBoundary = function(){
      return this.container.height() * this.scrollDistance + 1;
    };
    prototype.remaining = function(){
      return this._remaining || (this._remaining = this.elementBottom - this.containerBottom);
    };
    prototype.configWindowScroll = function(){
      this.containerBottom = this.container.height() + this.container.scrollTop();
      return this.elementBottom = this.elem.offset().top + this.elem.height();
    };
    prototype.configContainerScroll = function(){
      var containerBottom, elementBottom;
      containerBottom = this.container.height();
      return elementBottom = this.elem.offset().top - this.container.offset().top + this.elem.height();
    };
    return ScrollHandler;
  }(Debugger));
  module.exports = ScrollHandler;
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
